version: "3"
services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    env_file:
      - .env
    container_name: Go-URLShortener
    ports:
    - "5000:5000"
